"""
dummy_customer_api_extended.py

Extended version of the Raft dummy customer API that serves the demo
dataset generated by ml/generate_demo.py.

Identical interface to dummy_customer_api.py — same endpoints, same
response format, same port. The only difference is the dataset:
5 orders (default) → ~200 demo orders including ~10% out-of-policy orders.

The demo dataset (demo_orders.json) is SEPARATE from the training data
(extended_orders.json) so the anomaly model has never seen these orders —
its scoring on them is a genuine prediction, not a memory.

Start this instead of dummy_customer_api.py when using ML features:
    python dummy_customer_api_extended.py

The original dummy_customer_api.py is untouched as provided by Raft.
"""

import json
import random
from pathlib import Path
from flask import Flask, request, jsonify

app = Flask(__name__)

# ── Load extended dataset ──────────────────────────────────────────────────────

ORDERS_PATH = Path(__file__).parent / "ml" / "data" / "demo_orders.json"

try:
    with open(ORDERS_PATH) as f:
        ORDERS = json.load(f)
    print(f"Loaded {len(ORDERS)} demo orders from {ORDERS_PATH}")
except FileNotFoundError:
    print(f"ERROR: {ORDERS_PATH} not found.")
    print("Run python -m ml.generate_demo first to generate the demo dataset.")
    ORDERS = []


# ── Endpoints (identical to dummy_customer_api.py) ─────────────────────────────

@app.route("/api/orders", methods=["GET"])
def get_orders():
    """
    Returns orders as messy unstructured text.
    Identical interface to dummy_customer_api.py.
    """
    limit = request.args.get("limit", default=len(ORDERS), type=int)
    sample = random.sample(ORDERS, min(limit, len(ORDERS)))

    return jsonify({
        "status": "ok",
        "raw_orders": sample
    })


@app.route("/api/order/<order_id>", methods=["GET"])
def get_order_by_id(order_id):
    """
    Fetch a single order by scanning the text.
    Identical interface to dummy_customer_api.py.
    """
    for text in ORDERS:
        if order_id in text:
            return jsonify({
                "status": "ok",
                "raw_order": text
            })

    return jsonify({"status": "not_found"}), 404


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5001, debug=True)